1699297812308	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1699298810981	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1699298823920	Sync.Service	DEBUG	User-Agent: Firefox/119.0 (Linux x86_64) FxSync/1.121.0.20231023160744.desktop
1699298823920	Sync.Service	INFO	Starting sync at 2023-11-06 13:27:03 in browser session mDCa76O0maZ8
1699298823920	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1699298823921	Sync.Status	INFO	Resetting Status.
1699298823921	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1699298823922	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1699298823922	FirefoxAccounts	DEBUG	getOAuthToken enter
1699298823922	FirefoxAccounts	TRACE	getCachedToken returning cached token
1699298823922	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1699298823922	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1699298823931	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1699298823931	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.sys.mjs :: onStopRequest :: line 479\"  data: no]"}
1699298823937	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/147255507/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1699298823938	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1699298823938	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1699298823938	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1699298823938	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1699298823939	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
